### ISSUE TITLE
Incorporate Fog's data for Android TV Live Channels integration

### ISSUE THREAD

**Issue by TimDowker** [stvhwrd/SmoothStreamsTV-playlist#22]
Would it be possible to add Fog's data as a data source and generate a m3u8 files passed on it?

I'm trying to integrate SmoothStreams TV into my Android TV box (Nvidia Shield) Live Channels app.  I have found an app, TVirl (https://play.google.com/store/apps/details?id=by.stari4ek.tvirl&hl=en), which takes an m3u8 file and an XMLTV file for EPG data and puts it into the Live Channels app.  Fog has released the URLs for his data (see below).  This would allow me to run the script locally and generate the necessary m3u8 and XMLTV files for the TVirl app and have that integrated into the Live Channels app.

Is this at all possible?

Thanks in advance.

**Comment by TimDowker** [comment]
Forgot Fog's URLs

http://sstv.fog.pt/utc/xmltv.xml
http://sstv.fog.pt/utc/SmoothStreams.m3u8

**Comment by stvhwrd** [comment]
Hi Tim!

Very sorry for the delay in responding to your issue here, my GitHub notifier extension has been really unreliable.

I appreciate the feature suggestion, but as decided in the closing of issue #12, I'd like to keep this script as a self-contained module that can be built on by others.  I don't currently have the time (I'm a full time engineering student) or resources to adequately maintain enhancements like this.

Feel free to fork the project and add the features yourself.  I'll add your fork to the README if you do build on it.

I hope you can understand why I wouldn't want to half-ass an enhancement like this.  Thanks again for your effort and idea.

Cheers Tim 🍻
